### ISSUE TITLE
[1.18.2 Forge] Enabling buffer builder leak causes random crash.

### ISSUE THREAD

**Issue by TqLxQuanZ** [embeddedt/ModernFix#330] opened 2023-12-23 10:48 UTC
mixin.bugfix.buffer_builder_leak

For some reason in my modpack, whenever I activate this mixin, the game starts to crash randomly, not sure if it crashes on chunk generation or something else. (It doesn't crash immediately when loaded in the world but after some brief time)

The mod list is relatively quite big and I can't pinpoint which mod is causing it. Here's the latest log since it doesn't generate a crash log from it.

[latest.log](https://github.com/embeddedt/ModernFix/files/13758809/latest.log)

Some noticeable mention is that I uses lost cities and lost souls for custom city world gen, and it might be related to lost souls enemy starts to spawn and then crashing, but cannot confirm yet.

**Comment by embeddedt** [comment] 2023-12-23 15:32
Please run the game with this ModernFix build and send the log when it crashes.

[modernfix_test_build.zip](https://github.com/embeddedt/ModernFix/files/13759494/modernfix_test_build.zip)

**Comment by TqLxQuanZ** [comment] 2023-12-23 16:33
Thanks for the help!
It looks like it's from the flywheel side, inside the building generation there are some create related blocks/block entities.

[latest.log](https://github.com/embeddedt/ModernFix/files/13759644/latest.log)

**Comment by embeddedt** [comment] 2023-12-23 19:14
I discussed this with Pepper (one of the Flywheel devs) and we determined it's caused by Flywheel's batching engine replacing buffers in a way that ModernFix is not expecting. I've applied a workaround for the next release; if you have time, please confirm that the [beta](https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.18/Package.zip) fixes the issue.

**Comment by TqLxQuanZ** [comment] 2023-12-24 05:43
Tested with forge 1.18.2 with the setting enabled again, I didn't encounter any crash anymore during the building generations that contains create blocks in it.

**Comment by embeddedt** [comment] 2023-12-24 17:49
Fix released in 5.11.1

**Closed as completed by embeddedt** 2023-12-24 17:49 UTC
Labels: bug
