### ISSUE TITLE
Concurrent block/item color registration causes crash

### ISSUE THREAD

**Issue by MundM2007** [embeddedt/ModernFix#59] opened 2023-04-19 18:36 UTC
**Describe the Crash**
Added this mod to the modpack I'm working on is giving me this crash on Startup, it happens with different mods on each startup. (Once EvilCraft, once EvilCraft and Intergrated Dynamics and once AutoRegLib), without this mod the modpack works and doesn't crash. It seems to be happening on update checking. I've tried to add mods one by one (which I suspected to may cause this (mainly performance mods and mods they interact with)) without success.

**Screenshots**
![image](https://user-images.githubusercontent.com/85188362/233168037-52ef819b-bf8f-4601-8fdc-cfb8d1367572.png)

**Crash Report / log**
[latest.log](https://github.com/embeddedt/ModernFix/files/11276505/latest.log)
[crash-2023-04-19_20.29.17-fml.txt](https://github.com/embeddedt/ModernFix/files/11276509/crash-2023-04-19_20.29.17-fml.txt)

**Comment by embeddedt** [comment] 2023-04-19 19:58
I am pretty sure this crash is not caused by ModernFix. One or more mods are incorrectly registering block/item colors on a background thread instead of the main thread like they are supposed to. ModernFix makes this crash more likely to occur because there is less unnecessary work being done on startup, and so more mods have the opportunity to be doing this concurrently. But I think it can happen without it as well.

One solution I will probably implement from my end is adding hooks into the vanilla code to allow mods to do this safely, since there are many out there that have this problem.

------------------

@Asek3 I think synchronizing access to the map in `preRegisterColor` is going to be needed, even though this is really a bug in other mods.
https://github.com/Asek3/Rubidium/blob/8bb8de0fb32381d3eee1c844a3f96e98926b7ae8/src/main/java/me/jellysquid/mods/sodium/mixin/core/model/MixinBlockColors.java#L6

Relevant issue: https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/71

**Comment by embeddedt** [comment] 2023-04-19 20:06
Correction: I already fixed this for vanilla, the fix just doesn't apply to Rubidium's version of the same code because I didn't anticipate it being an issue. Should be a simple patch on my end.

**Comment by embeddedt** [comment] 2023-04-19 20:12
[modernfix.zip](https://github.com/embeddedt/ModernFix/files/11277257/modernfix.zip)

I think this beta should fix your problem. This will be included in the next release.

**Comment by MundM2007** [comment] 2023-04-20 18:23
Hey, that fixed that issue! Thanks for the quick response and fixing it even though it isn't really caused by your mod.
Though i have found an incompatability with the spark mod (only spark and your new modernfix mod), crash report and og below:
(If I should open a new issue for this tell me and I will do so)
[latest.log](https://github.com/embeddedt/ModernFix/files/11289288/latest.log)
[crash-2023-04-20_20.21.05-fml.txt](https://github.com/embeddedt/ModernFix/files/11289293/crash-2023-04-20_20.21.05-fml.txt)

**Comment by embeddedt** [comment] 2023-04-20 23:20
[modernfix.zip](https://github.com/embeddedt/ModernFix/files/11291067/modernfix.zip)

Thanks, fixed.

**Comment by Asek3** [comment] 2023-04-21 06:56
So, is my interaction in Rubidium still needed? I mean compatibility with other mods maybe, not only ModernFix

**Comment by embeddedt** [comment] 2023-04-21 17:25
I would suggest you make that map thread-safe, as otherwise modders will likely blame Rubidium since the crash happens within its mixin. But this is really a problem with other mods for calling this off the client thread in the first place.

**Comment by MundM2007** [comment] 2023-04-21 18:16
The modpack loaded up now! thanks! And I gotta say absolute awesome mod. It cut down loading times from 200 seconds to 100 seconds. Keep it going.

**Comment by embeddedt** [comment] 2023-04-29 15:50
Thanks for the kind words. The latest release should also include this fix now.

**Closed by embeddedt** 2023-04-29 15:50 UTC
