### ISSUE TITLE
Passable Foliage Incompatibility? 

### ISSUE THREAD

**Issue by wanji404** [embeddedt/ModernFix#99] opened 2023-05-14 16:28 UTC
Adding this ModernFix resulted in  Passable Foliage not working anymore？
link：https://www.curseforge.com/minecraft/mc-mods/passable-foliage
Minecraft version：1.18.2forge
ModernFix version：2.5.2forge

**Comment by embeddedt** [comment] 2023-05-14 22:16
With only ModernFix and Passable Foliage installed everything appears to work normally.

**Comment by Kasualix** [comment] 2023-05-15 11:42
1.16.5, cannot reproduce this incompatibility too

**Comment by MageInBlack** [comment] 2023-05-16 00:55
I experience the similar issue. After painstakingly disabling most of my mods i figured out that after number of loaded mods grows to 94 (counter in minecraft main menu) suddenly leaves become solid. I will test several configurations of this to determine if mod amount have anything to do with it and post it later. And possibly report it to passable foliage github

**Comment by embeddedt** [comment] 2023-05-16 00:57
It's most likely an incompatibility with the `mixin.perf.reduce_blockstate_cache_rebuilds` option in ModernFix, if you wish to test disabling that.

**Comment by MageInBlack** [comment] 2023-05-16 01:29
> It's most likely an incompatibility with the `mixin.perf.reduce_blockstate_cache_rebuilds` option in ModernFix, if you wish to test disabling that.

Yes, it seems to be the issue. Tested it with 94 and my own modpack of over 300. I wonder why the magic number is 94 though. Leaves are passable now with disabling the `mixin.perf.reduce_blockstate_cache_rebuilds`

**Comment by embeddedt** [comment] 2023-05-16 02:23
Please re-enable the option and test with the latest development build (link is in the README); this should be fixed now.

**Comment by wanji404** [comment] 2023-05-16 02:58
Yes, it fixed the problem. Thank you

**Comment by MageInBlack** [comment] 2023-05-16 05:11
The dev build works on 1.19.2 as well. Thanks for the quick fix (also the mod is pretty awesome by itself)

**Comment by SettingDust** [comment] 2023-05-17 02:23
Hm. Modify with MixinExtras will provide more compatibility I think

**Comment by embeddedt** [comment] 2023-05-17 02:24
I've already adjusted the mixin for better compatibility in the current dev builds.

**Comment by embeddedt** [comment] 2023-05-19 23:47
Fixed in latest releases.

**Closed by embeddedt** 2023-05-19 23:47 UTC
Labels: fixed in dev
