### ISSUE TITLE
Dynamic Resources makes some blocks not render in Bumblezone

### ISSUE THREAD

**Issue by vedranskarica** [embeddedt/ModernFix#243] opened 2023-09-21 10:23 UTC
Fabric, MC 1.20.1
on latest versions of modernfix and bumblezone (Bumblezone 7.0.3, ModernFix 5.7.2) but probably earlier versions as well,
some blocks (porous honeycomb block and empty honeycomb brood block) don't render:
![2023-09-21_11 44 07](https://github.com/embeddedt/ModernFix/assets/7735672/666dd896-82b6-4b98-8676-ad3a8e141ffa)
with dynamic resources turned off:
![2023-09-21_11 43 20](https://github.com/embeddedt/ModernFix/assets/7735672/fe31c78d-97a8-49f3-bcc9-fac034ab4007)

Tested and verified with a minimum mod set:
bumblezone 7.0.3
modernfix 5.7.2
fabric API 0.89.0
midnightlib 1.4.1.1 (bumblezone dependancy)
modmenu 7.2.2

**Comment by TelepathicGrunt** [comment] 2023-09-21 17:58
@vedranskarica the issue more likely belongs on my Bumblezone repo and not modernfix’s

**Comment by embeddedt** [comment] 2023-09-23 02:06
Closing, as I believe this is caused by Bumblezone not using the official Fabric API for block models, which will be fixed in an eventual update.

**Closed as not planned by embeddedt** 2023-09-23 02:06 UTC

**Comment by TelepathicGrunt** [comment] 2023-09-24 00:22
@vedranskarica v7.0.5 Bumblezone should fix this now
