### ISSUE TITLE
User datapack gets forcefully reordered after mod datapacks

### ISSUE THREAD

**Issue by 2929762171** [embeddedt/ModernFix#239] opened 2023-09-17 02:00 UTC
modernfix-forge-5.7.2+mc1.16.5
(Poor English)
【JER】
Before:
![image](https://github.com/embeddedt/ModernFix/assets/98941945/ef7ae9cd-abc7-4c60-a6a4-70bc8fb0898f)

I can't see mods resource:
![image](https://github.com/embeddedt/ModernFix/assets/98941945/a04e1352-e571-4826-8364-833285691fc2)

I changed to false:
![image](https://github.com/embeddedt/ModernFix/assets/98941945/a7de36a2-4653-496c-a48b-b312bd628fce)
Then it became normal:
![image](https://github.com/embeddedt/ModernFix/assets/98941945/f1a8da08-ba22-4432-8f22-e0fdbfae368a)

Maybe you should notice this.

【datapack】
You can see I had load a custom datapack, I change someting with vanilla data like loot tables, and set it to load after vanilla.
![image](https://github.com/embeddedt/ModernFix/assets/98941945/1ef62ab8-2bdb-403b-86a6-2ff898108881)
![image](https://github.com/embeddedt/ModernFix/assets/98941945/257d3bbf-8155-4b59-b02f-5668c5ef5530)

Datapack worked as expected, but I found that it will break mods'loot tables,  just like it load at last and cover other mods' modification of vanilla.
![image](https://github.com/embeddedt/ModernFix/assets/98941945/46186a07-fb61-4ac5-8b5e-418cd1373ffc)
![image](https://github.com/embeddedt/ModernFix/assets/98941945/f484f507-5287-459a-8515-e2851929f420)
![image](https://github.com/embeddedt/ModernFix/assets/98941945/8e8dd81e-e30e-4904-b160-d15e9e1d0cea)
As you can see, I tested a lot...

The problem is, I already set it to load after vanilla, not at last.
When I remove modernfix OR my datapack, problem can be solved.
![image](https://github.com/embeddedt/ModernFix/assets/98941945/71670633-1ce8-4524-a2b9-0bd242e25995)

I have no idea which mixin cause this problem...

**Comment by embeddedt** [comment] 2023-09-17 02:03
Hmm, what happens if `mixin.perf.resourcepacks` is disabled? (This will heavily impact launch time, but is worth checking.)

**Comment by 2929762171** [comment] 2023-09-17 02:12
> Hmm, what happens if `mixin.perf.resourcepacks` is disabled? (This will heavily impact launch time, but is worth checking.)

Still. I try yesterday.

**Comment by embeddedt** [comment] 2023-09-17 02:17
Interesting. Only other option I can think of to try is `mixin.perf.skip_first_datapack_reload`. 

Aside from that, I have anecdotally seen issues with Forge changing mod datapack order by itself, at least on 1.16, so it's possible it ends up moving your datapack to the end internally.

**Comment by 2929762171** [comment] 2023-09-17 02:34
> 有趣的。我能想到尝试的唯一其他选择是`mixin.perf.skip_first_datapack_reload`。
> 
> 除此之外，我还听说过 Forge 自行更改 mod 数据包顺序的问题，至少在 1.16 上是这样，所以它最终可能会在内部将您的数据包移动到末尾。

Still. I tried it yesterday, too.
And I think maybe it's not a Forge problem, because everything work correctly without modernfix, so I tested a lot before I pose this issue. Then the question finally points to modernfix.

**Comment by embeddedt** [comment] 2023-09-17 16:17
In a fairly simple instance with ModernFix and a few other mods, I tried making a test datapack that overwrites a recipe from a mod, and moving it to be immediately after vanilla (as you did), and it still seems to work correctly. The datapack's changes are ignored since the mod comes after it in the list.

Can you send your `latest.log` file, so I can compare the pack order it shows there with what the `/datapack` command claims?

**Comment by 2929762171** [comment] 2023-09-17 17:19
> In a fairly simple instance with ModernFix and a few other mods, I tried making a test datapack that overwrites a recipe from a mod, and moving it to be immediately after vanilla (as you did), and it still seems to work correctly. The datapack's changes are ignored since the mod comes after it in the list.
> 
> Can you send your `latest.log` file, so I can compare the pack order it shows there with what the `/datapack` command claims?

Did your datapack contain other parts of the vanilla?  Especially chest loot table， and the most obvious problem is here.
![image](https://github.com/embeddedt/ModernFix/assets/98941945/c8863776-12be-4d27-a31c-10a837b85e64)
![image](https://github.com/embeddedt/ModernFix/assets/98941945/c25fbefd-f689-456e-9493-2105e17841d9)

**Comment by embeddedt** [comment] 2023-09-23 02:09
No, I was trying to make the simplest datapack I could think of as I had limited time to test it. :sweat_smile: 

If you could give an example of one mod that adds to a vanilla loot table, and provide a corresponding datapack that overwrites the same loot table, I can look into this again. The simplest setup that can reproduce this is ideal for debugging.

**Comment by 2929762171** [comment] 2023-09-23 02:17
[vanilla+++.zip](https://github.com/embeddedt/ModernFix/files/12705410/vanilla%2B%2B%2B.zip)
Try this?

**Comment by embeddedt** [comment] 2023-09-24 14:30
Which mod should I use with this datapack?

**Comment by 2929762171** [comment] 2023-09-24 14:39
> 我应该将哪个模组与此数据包一起使用？

Any mod that modifies the chest loot table.
You can try : rings of ascension, artifacts...

**Comment by 2929762171** [comment] 2023-09-24 14:45
By the way, this problem will not happen on FarmersDelight, its resources can always appear in the chest.

**Comment by embeddedt** [comment] 2023-09-24 15:52
I was able to reproduce the issue with Artifacts & the datapack added after vanilla. However, when I removed ModernFix the behavior was exactly the same. Artifacts loot was not added to the chest if the datapack was present.

I looked into the Forge/Artifacts code that's responsible for loading of loot tables, and it looks like modded loot is only supposed to be injected into loot tables added by the vanilla datapack. If a custom datapack is added that overwrites loot tables, mods' loot will not be added.

In other words, the code appears to intentionally be written for what you are doing not to work - if you want modded loot to be applied, you cannot be replacing the vanilla loot tables yourself using a datapack. A better option is probably to use KubeJS or CraftTweaker and write a simple script to modify the loot tables at runtime.

(For the interested reader with technical understanding of the game, [here](https://github.com/MinecraftForge/MinecraftForge/blob/09f1b8d43856643e4ab36d9d64e2176c440a3e72/patches/minecraft/net/minecraft/loot/LootTableManager.java.patch#L10) is where the datapack is checked for being vanilla, and [here](https://github.com/MinecraftForge/MinecraftForge/blob/09f1b8d43856643e4ab36d9d64e2176c440a3e72/src/main/java/net/minecraftforge/common/ForgeHooks.java#L884-L885) is where the loot table modification event is skipped if the original loot table is found to be custom, i.e. added by a datapack.)

**Closed as not planned by embeddedt** 2023-09-24 15:52 UTC

**Comment by 2929762171** [comment] 2023-09-24 15:57
> However, when I removed ModernFix the behavior was exactly the same.

It seems that you forgot to change the loading order.

**Comment by embeddedt** [comment] 2023-09-24 16:08
No, I put the datapack right after vanilla, same as you.

**Comment by 2929762171** [comment] 2023-09-24 16:11
> 不，我把数据包放在原版之后，和你一样。

Fine, thanks for your work.
