### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by VicoIlFico** [embeddedt/ModernFix#170] opened 2023-07-20 09:49 UTC
Updating from ModernFix 5.2.5 to Moderfix 5.3.1 for Fabric 1.20.1 causes some blocks to not render properly (example chests).
This only happens in the new version afaik and reverting back fixes it. Also this was tested with additional optimization mods such as the latest version of Enhaced Block Entities

5.2.5

![2023-07-20_11 32 47](https://github.com/embeddedt/ModernFix/assets/109347883/0c898dc6-3762-4fc6-9ac5-dee68617cbfa)

5.3.1

![2023-07-20_11 34 32](https://github.com/embeddedt/ModernFix/assets/109347883/93a52d01-5cd8-4564-a8db-efbe6817020f)

5.2.5

[5.2.5.txt](https://github.com/embeddedt/ModernFix/files/12104632/5.2.5.txt)

5.3.1

[5.3.1.txt](https://github.com/embeddedt/ModernFix/files/12104636/5.3.1.txt)

**Comment by embeddedt** [comment] 2023-07-20 14:26
Think this is a duplicate of #169, update Fabric API for now.

**Closed as not planned by embeddedt** 2023-07-20 14:26 UTC
