### ISSUE TITLE
[1.16.5] Servers frequently not loading up past "SimpleReloadableResourceManager"

### ISSUE THREAD

**Issue by antibang** [embeddedt/ModernFix#110] opened 2023-05-26 01:15 UTC
I run 2 servers running my modpack, though one is slightly different than the other. However, they both experience the same issue. We noticed that the servers weren't booting up by themselves after restart *a lot* of the time, but not every time, and seemingly become stuck on "SimpleReloadableResourceManager" during startup. This results in me or my staff having to forcibly kill the server and boot it up. This doesn't always work and is sometimes needed several times before it finally fully starts.

I removed the mod just to make sure something else wasn't the culprit, but the issue went away after removal. When readded, the issue came back. I tried disabling a few mixins, but wasn't having any success and thought I should submit an issue before continuing. I've included both the latest log and debug.

[latest.log](https://github.com/embeddedt/ModernFix/files/11570391/latest.log)

[debug.log](https://github.com/embeddedt/ModernFix/files/11570392/debug.log)

**Comment by embeddedt** [comment] 2023-05-26 02:39
I will check the log in the morning. In case it doesn't show anything
helpful (not uncommon for freezes) do you know how to get a thread dump
from the server?

**Comment by antibang** [comment] 2023-05-26 04:13
Do you need the dump as the problem occurs? I'm not very familiar with thread dumps.

**Comment by embeddedt** [comment] 2023-05-26 15:19
Yes; if you're not familiar with thread dumps this debug build will perform a thread dump by itself every 60 seconds, so wait for the freeze to happen, wait another minute or so, and then send the log.
[debugbuild.zip](https://github.com/embeddedt/ModernFix/files/11576658/debugbuild.zip)

**Comment by antibang** [comment] 2023-05-27 07:27
I apologize for the slow reply. Here's the log using the build:

[latest.log](https://github.com/embeddedt/ModernFix/files/11581221/latest.log)

Could this be due to `mixin.perf.kubejs` ?

**Comment by embeddedt** [comment] 2023-05-27 13:05
It's possible but doubtful; that option only makes some optimizations to the KubeJS reload process and I'd expect it to outright crash if it really had issues. (Additionally it's a very old feature that's been present since the early days of the mod.)

The thread dump is strange and doesn't really give any insight into why the server thread is waiting for the resource reload still. Is it possible for me to get a ZIP of the mods and config in use for testing locally?

**Comment by embeddedt** [comment] 2023-05-27 21:44
I assume BaerCraft is the modpack you are running on your server. I tested locally with the latest server pack (0.8.5.5) and it can consistently launch each time I've tried it. So I'm not sure if the problem is with ModernFix, or something on your specific server.

**Comment by antibang** [comment] 2023-05-30 01:55
Yes, I can zip them!

[Couldn't upload to GitHub, so here's the Google Drive link.](https://drive.google.com/file/d/1IXBTBR2zPFGC_3m0g87CfeUi9fZFKMvO/view?usp=sharing)

Additionally, I should possibly mention that my co-dev's server (not running BaerCraft) also experiences this issue. I do know they use a few of the same server-sided mods, but I'm not sure exactly what specifically.

**Comment by embeddedt** [comment] 2023-06-25 16:41
Closing as I'm not sure I can do anything else about this, but let me know if it still occurs with the latest version (5.0.4 or newer).

**Closed by embeddedt** 2023-06-25 16:41 UTC
