### ISSUE TITLE
Forge 1.19.2 - crashing server

### ISSUE THREAD

**Issue by kitovoi111** [embeddedt/ModernFix#368] opened 2024-02-17 05:50 UTC
### Bug Description

[crash-2024-02-17_08.42.32-server.txt](https://github.com/embeddedt/ModernFix/files/14317869/crash-2024-02-17_08.42.32-server.txt)

### Reproduction Steps

start server...
waiting time..
crash..

### Log File

[2024-02-17-1.log](https://github.com/embeddedt/ModernFix/files/14317870/2024-02-17-1.log)

**Comment by embeddedt** [comment] 2024-02-17 16:07
This crash is usually caused by another mod accessing the world's random number generator on the wrong thread. I recommend installing a tool like https://legacy.curseforge.com/minecraft/mc-mods/uwrad-forge and letting it crash a second time, it will provide more information as to what mod caused the crash.

Closing as this doesn't look like ModernFix's fault.

**Closed as not planned by embeddedt** 2024-02-17 16:07 UTC
