### ISSUE TITLE
[1.20.1] FramedBlocks (and possibly others) started taking much longer to load

### ISSUE THREAD

**Issue by dima-dencep** [embeddedt/ModernFix#293] opened 2023-11-10 20:31 UTC
After updating modernfix from 5.9.0 to 5.9.1, FramedBlocks started taking a little over a minute to load
- https://spark.lucko.me/PYrYRwFwIW (Worker-ResourceReload-10)

Before update, FB only took two seconds
- https://spark.lucko.me/8zEs2mXIwi (Worker-ResourceReload-3)

What do I need to do (besides disabling dynamic resources) to fix this?

<details>
The profiler lists version 5.9.2, but I know this started happening between 5.9.0 and 5.9.1.
</details>

**Comment by embeddedt** [comment] 2023-11-10 20:45
Thanks for the report; it seems to be a regression caused by porting the Fabric implementation of dynamic resources to Forge. The [beta](https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip) should restore previous performance.

**Comment by embeddedt** [comment] 2023-11-12 21:58
Fixed in 5.9.3.

**Closed as completed by embeddedt** 2023-11-12 21:58 UTC
Labels: bug, fixed in beta
