### ISSUE TITLE
Parallelize Model Loading Crash 1.16.5

### ISSUE THREAD

**Issue by iamc24** [embeddedt/ModernFix#53] opened 2023-04-04 22:18 UTC
game crashes when launching when mixin.perf.parallelize_model_loading.multipart and mixin.perf.parallelize_model_loading are enabled; seems like it might be related to the betterend mod

didn't see an existing issue that seemed like it related to this

[crash-2023-04-04_15.03.46-client.txt](https://github.com/embeddedt/ModernFix/files/11153656/crash-2023-04-04_15.03.46-client.txt)

**Comment by embeddedt** [comment] 2023-04-04 22:19
Does https://www.curseforge.com/minecraft/mc-mods/better-end-potato-edition crash?

**Comment by iamc24** [comment] 2023-04-04 22:27
no, however i was adding performance and bugfix mods to an existing modpack. do you know if potato edition would work as a drop-in replacement that wouldn't break quests, recipes, etc?

**Comment by embeddedt** [comment] 2023-04-04 23:49
I doubt it breaks any quests or recipes but @Kasualix can confirm. However, if you plan on connecting to a multiplayer server it might be an issue; in that case you can just disable parallelize_model_loading in the config.

**Comment by Kasualix** [comment] 2023-04-05 04:36
> do you know if potato edition would work as a drop-in replacement that wouldn't break quests, recipes, etc?

It wouldn't break. But I did disable two ugly biomes in the config (tweak their generation chance to 0.0), so you'd better tweak the config to let them generate (You can search 0.0 in VSCode's searching fuction to find them easily) if the modpack has biomes-related quests (such as finding biomes to complete quests)

**Comment by embeddedt** [comment] 2023-04-06 16:24
Closing as the issue is caused by [an invasive mixin](https://github.com/Beethoven92/BetterEndForge/blob/master/src/main/java/mod/beethoven92/betterendforge/mixin/ModelBakeryMixin.java) in the original Forge port which I cannot fix directly, and there is a more maintained port available.

**Closed by embeddedt** 2023-04-06 16:24 UTC
