### ISSUE TITLE
Every entity is invisible during gameplay, 1.19.2

### ISSUE THREAD

**Issue by SireAwfulThe1st** [embeddedt/ModernFix#34] opened 2023-03-06 15:17 UTC
Tried using this mod for the first time in 1.19.2. Everything was going well up until I noticed that there's an issue in which every single entities, from mobs until block entities e.g chest are invisible, maybe you could investigate this bug?

**Comment by Kanzaji** [comment] 2023-03-08 18:55
I am fairly sure this isn't an issue with ModernFix, unless it can be easily reproduced. Since 1.16.5 there is an issue with Invisible Entites with Configured / Alex Mobs mod, so if you have that mod installed and opened a Mod Menu / Mod Settings menu, that is probably the cause.

**Comment by Kasualix** [comment] 2023-03-09 06:56
Agree with Kanzaji.

**Comment by embeddedt** [comment] 2023-03-12 02:29
This issue report needs more information.

* What other mods are installed? Please try to reproduce with only a few mods.
* Please send the `latest.log` file from a game session where you could reproduce the issue.

Aside from that, I agree with the above - ModernFix doesn't currently patch anything relating to entity rendering so it's unlikely to be the cause.

**Comment by embeddedt** [comment] 2023-03-24 00:55
Closing as this issue report is not actionable as-is. If you are still able to reproduce this with the latest version of ModernFix for 1.19, please comment with more info and I will reopen.

**Closed by embeddedt** 2023-03-24 00:55 UTC
Labels: invalid
