### ISSUE TITLE
1.20.1 - Crash on Forge ver. 47.2.16

### ISSUE THREAD

**Issue by CrimsonsArt** [embeddedt/ModernFix#309] opened 2023-11-30 20:10 UTC
I'm facing consistent crashes when trying to launch ModernFix for Minecraft 1.20.1 with Forge - 47.2.16.

Steps to reproduce:
1. Create a clean new modpack through the CurseForge client.
2. Choose Forge version 47.2.16.
3. Install only ModernFix.
4. Launch game, crash to exit code: 1.

Here is my [latest.log](https://github.com/embeddedt/ModernFix/files/13517360/latest.log)

**Comment by embeddedt** [comment] 2023-11-30 20:45
It's caused by an internal change in Forge and will be fixed in the next release. For now you can add `mixin.perf.fast_registry_validation=false` to `config/modernfix-mixins.properties` to work around it.

**Comment by Coraline774477** [comment] 2023-12-02 13:58
So how am I supposed to add that as a workaround when the mod's settings isn't in a normal config file like any other mod???
It's latterly a properties file and I clearly don't know what I'm doing or going to do with a properties file of a mod? Especially a performance mod?!?
I don't have any programs that opens and lets me edit a properties file like this, the only thing that allows me to open that file is Ultra File Opener and I don't have any money or even want to register to Ultra File Opener when it's possibly just a file viewer, as well as I'm unwilling to get any other program just to edit ModernFix's configuration settings unlike notepad or notpad++ which is what I'm more used too and understand how to use those for a traditional mod configuration file/folder!

So I'm either gonna downgrade my forge version to 47.2.14 or lower to a point before Lex made those internal changes to forge or I just simply uninstall ModernFix until you upload a fix for Lex's messy fixes/changes..

Which I don't really want to do either one of those options since I prefer to stay up-to-date with forge (1.20.1) as well as to keep ModernFix for what it provides to the game that Mojang should've added into vanilla a long time ago..

Intentionally I had plans to start a new 1.20.1 world that's basically a port of my last remaining 1.19.2 world (still gonna be playing on there btw) but I guess that I'll have to change my plans by playing on a different viersion other than 1.20.1..for now...

I'm not gonna be on 1.20.2 just yet but when I do I'll be tying out NeoForge for the first time.
If I end up liking NeoForge then I would never go back to *LexForge ever again except for Minecraft 1.18.2 (for Cora World Guns that has Timeless and Classics; Reforged), 1.19.2 (Cora World 3) and 1.20.1 (Cora World: The Twilight Forest and the new world that I plan on making)

*Why I'm calling forge "LexForge" is because I want too as it's new nickname for an aging old modloader that should've died along time ago which now it will since NeoForge is going to be LexForge's successor!
It's about time that LexForge dies since Lex braught it down into the ground, six feet down into the ground that is!)

**Comment by embeddedt** [comment] 2023-12-02 15:19
If you don't want to use the config file, your options are:

1. Use the beta linked in the [README](https://github.com/embeddedt/ModernFix#readme) on the repository's main page.
2. Downgrade Forge to an earlier version that doesn't include that change (as mentioned)
3. Wait patiently for a new release of ModernFix, which will be coming as soon as I have time to validate and release it properly.

FWIW, the `.properties` file is just a regular text file, and you should be able to use Notepad++ on it like any other config file.

**Comment by embeddedt** [comment] 2023-12-04 02:18
This is fixed in 5.10.0.

**Closed as completed by embeddedt** 2023-12-04 02:18 UTC
Labels: bug, fixed in beta
