### ISSUE TITLE
Ender Portal Sand Gone

### ISSUE THREAD

**Issue by hybcp118** [embeddedt/ModernFix#404] opened 2024-05-11 10:34 UTC
### Bug Description

I have a bug where when I drop sand on the portal in Ender, the sand disappears without going to the sponge point.
I use a translator, so there may be a wrong translation.

### Reproduction Steps

i don't know

### Log File

i don't know

**Comment by embeddedt** [comment] 2024-05-12 01:58
This does not occur with the default ModernFix settings. However, if `mixin.perf.remove_spawn_chunks` is enabled, the spawn chunks are not kept loaded. In vanilla, when an end portal attempts to teleport a falling block to the overworld spawn point, it will teleport to Y -64 if the spawn chunks aren't loaded. This will cause it to immediately fall into the void and despawn, which gives the illusion of it not teleporting.

This is not a bug, since that option is not enabled by default, and disabling spawn chunks is expected to cause behavioral changes from vanilla. However, I can tweak the game so that entities will still go through portals as intended.

**Comment by embeddedt** [comment] 2024-06-05 00:04
Fix released in 5.18.0.

**Closed as completed by embeddedt** 2024-06-05 00:04 UTC
Labels: enhancement, fixed in beta
