### ISSUE TITLE
block texture corruption on fabric

### ISSUE THREAD

**Issue by Abalieno** [embeddedt/ModernFix#91] opened 2023-05-09 11:31 UTC
Tried loading a large modpack, everything appears fine, but there's some corruption.

It seems to happen on different block, but it looks like this:

![uio;l](https://github.com/embeddedt/ModernFix/assets/4656436/a8d60c72-ee30-4d9d-8839-ae4d524bafbc)

This is a machine, but in a different test I saw it happen with a grass block. Both cases had only corrupted sides.

Using modernfix-mc1.19.2-fabric-3.5.2

**Comment by embeddedt** [comment] 2023-05-09 14:05
If you are able to get it to happen consistently, it would be useful to know if disabling `mixin.perf.faster_texture_stitching` in the config fixes it.

**Comment by Abalieno** [comment] 2023-05-09 16:31
Yes, it seems to fix it.

**Comment by Abalieno** [comment] 2023-05-12 11:46
modernfix-mc1.19.2-fabric-3.5.2-11-g6eddbd1 to >modernfix-mc1.19.2-fabric-3.5.2-14-g2de8f02

texture corruption is back

**Comment by embeddedt** [comment] 2023-05-12 13:38
It hasn't been fixed yet and I'm not sure exactly what the problem is as it only seems to happen to a few people.

**Comment by embeddedt** [comment] 2023-05-19 23:58
Can you get this to occur with Sodium disabled? It might be https://github.com/IrisShaders/Iris/issues/1726, which was eventually tracked down to be a bug in Sodium, but was only fixed for 1.19.3+ versions.

**Comment by Abalieno** [comment] 2023-05-20 03:28
I'll try but I don't use Iris, and Sodium without Modernfix doesn't show problems.

**Comment by Abalieno** [comment] 2023-05-20 04:08
It's proving tricky to test.

Removed modernfix config, removed sodium and related mods > no problem
reloaded to be sure > no problem
restored sodium and co. > ... no problem
reloaded a second time > still no problem

**Comment by embeddedt** [comment] 2023-05-20 17:41
It was an issue in Sodium, not Iris; it's just that Iris backports the fix to older versions (since Sodium is not updated for 1.19.2 and older). I think having Iris installed but not enabling a shader would be enough to take advantage of the fix.

**Comment by Abalieno** [comment] 2023-05-21 02:53
![uikluil](https://github.com/embeddedt/ModernFix/assets/4656436/e63c92a5-dfb3-458b-886f-2f5794895d44)

I also have this problem that I'm ... almost sure it's also due to Modernfix.

Kubejs client scripts seem to be working oddly. I get this random spam, rather than 1 line. Other items have a varied number of repeated lines, and in a few cases, no custom messages appearing where they should be.

It gets fixed immediately with /kubejs reload client_scripts

But it seems the problem only shows up when I use Modernfix.

**Comment by embeddedt** [comment] 2023-05-21 18:31
Oops, closed the wrong issue.

**Comment by embeddedt** [comment] 2023-05-21 18:32
It wouldn't surprise me if this is a bug in KubeJS which ModernFix reveals as a result of some speedup. As far as I know 1.19 KubeJS builds are relatively unreliable and a bunch of packs are reloading scripts a second time to work around problems.

**Comment by Abalieno** [comment] 2023-05-22 02:40
Yes, including mine :)

**Comment by embeddedt** [comment] 2023-05-31 14:23
Are you able to reproduce the KubeJS issue consistently? Might be fixed now in the latest dev version, there was a conflict between some NBT logic in KubeJS and one of ModernFix's optimizations.

**Comment by Abalieno** [comment] 2023-06-03 03:22
It seems to be working, but I need to test more to be sure.

**Comment by Abalieno** [comment] 2023-06-03 17:18
Nope, still having problems and duplicated tooltips. Hopefully the new version of kubejs coming out soon fixes the whole thing:

**Comment by embeddedt** [comment] 2023-06-03 17:19
I don't think this one is caused by ModernFix, looks to be related to REI async search.

**Comment by Abalieno** [comment] 2023-06-03 17:25
It's what happened in the post with the image above. I cannot test further now, but last time I tried it seemed to resolve without Modernfix.

**Comment by embeddedt** [comment] 2023-06-03 17:27
It's a ConcurrentModificationException which means it won't happen consistently. Sometimes ModernFix's performance improvements cause them to occur more regularly.

**Comment by embeddedt** [comment] 2023-06-25 16:40
I think the original texture issue can be resolved by installing Iris for 1.19.2 and older, and I am pretty sure the KubeJS issue is something else, so I'll close this.

**Closed by embeddedt** 2023-06-25 16:40 UTC
Labels: fabric
