### ISSUE TITLE
EMF 0.2.8 compat issues with modernfix forge 1.19.2 ver. 3.5.1-3.5.2

### ISSUE THREAD

**Issue by tenzedkariyu19** [embeddedt/ModernFix#85] opened 2023-05-08 06:36 UTC
when using https://www.curseforge.com/minecraft/mc-mods/entity-model-features and combining it with the Fresh Animations resource pack the animations for mobs don't properly load. when using modernfix version 3.5.0 the animations work completely fine.
https://www.curseforge.com/minecraft/texture-packs/fresh-animations

**Comment by embeddedt** [comment] 2023-05-08 15:19
Please test again with 3.5.2.

**Comment by tenzedkariyu19** [comment] 2023-05-09 00:24
did you release 3.5.2? i cant seem to find the build on CF

**Comment by tenzedkariyu19** [comment] 2023-05-09 03:39
ive ran 5 test and the animations are missing for the zombie, skeleton, villager, piglin, zombified piglin and possibly other mobs but most notably those 5. the villager had an animation 2/5 of those test but all the others didn't. I went back to version 3.5.0 and ran 5 test and all the animations properly loaded

**Comment by embeddedt** [comment] 2023-05-15 00:33
Still can't reproduce with only ModernFix 3.5.2, FerriteCore, EMF and ETF, so it's probably a mod conflict.

**Comment by Redls07** [comment] 2023-06-03 02:47
I can't reproduce it either. Tested with EMF 0.2.8 & ModernFix 3.5.2 and EMF 0.2.9 & ModernFix 3.7.0. Try to update these mods to the latest versions, and also try to test only these mods, without any others, if you have them (not counting ETF, of course)

**Comment by embeddedt** [comment] 2023-07-03 19:16
Going to close this for now as I can't reproduce it, and therefore have no way to fix it.

**Closed by embeddedt** 2023-07-03 19:16 UTC
Labels: help wanted, cannot reproduce
