### ISSUE TITLE
Can this error possibly be looked into, and maybe even fixed by this mod?

### ISSUE THREAD

**Issue by Sunconure11** [embeddedt/ModernFix#235] opened 2023-09-10 16:57 UTC
https://user-images.githubusercontent.com/5614902/266851142-f75fea21-7b85-4ccc-b6c8-d76cc9e2ad5b.png

[latest.log](https://github.com/embeddedt/ModernFix/files/12569322/latest.log)

There are multiple conflicting statements as to what causes this, ranging from packet stuff, to statistics. Maybe this mod could fix it?

**Comment by embeddedt** [comment] 2023-09-10 17:26
The most likely culprit I can think of is the registry being too large... possibly due to the number of mods installed. I don't think this is being caused by ModernFix. You could try enabling `debugPrintMessages` in the Connectivity config and see if it shows anything more useful in the log.

**Comment by Sunconure11** [comment] 2023-09-10 17:27
I wasn't saying this was caused by ModernFix, I was asking if this is a thing that can be fixed by it.

**Comment by embeddedt** [comment] 2023-09-10 17:28
There isn't enough information for me to fix anything at the moment; networking errors are very difficult to debug.

**Comment by Sunconure11** [comment] 2023-09-10 17:32
https://github.com/TonimatasDEV/PacketFixer/issues/21

Well, I've also been discussing it over at PacketFixer, just in case it can be fixed there.

**Comment by Sunconure11** [comment] 2023-09-19 23:27
https://github.com/TonimatasDEV/PacketFixer/issues/22

**Comment by Sunconure11** [comment] 2023-09-19 23:27
There has since been far more info @embeddedt obtained. I suggest looking over those two issues.

**Comment by Sunconure11** [comment] 2023-09-21 04:22
@embeddedt @tonimatasdev

https://github.com/terrarium-earth/Chipped/issues/214

This might be the cause

**Comment by embeddedt** [comment] 2023-11-07 14:17
It is not clear exactly what fix (if any) would resolve this issue, and at this moment I don't have time to debug the network subsystem further. As this is not a ModernFix bug, I'll close this for now.

**Closed as not planned by embeddedt** 2023-11-07 14:17 UTC

**Comment by TonimatasDEV** [comment] 2023-11-07 14:27
> It is not clear exactly what fix (if any) would resolve this issue, and at this moment I don't have time to debug the network subsystem further. As this is not a ModernFix bug, I'll close this for now.

Don't worry, I've already fixed this in Packet Fixer.

**Comment by embeddedt** [comment] 2023-11-07 14:29
Awesome! I will keep it in mind if I run into the error myself. :slightly_smiling_face:
