### ISSUE TITLE
Crash when interacting with Tinkers crafting bench

### ISSUE THREAD

**Issue by GermanPlasma** [embeddedt/ModernFix#18] opened 2023-02-13 06:05 UTC
I'm sorry to leave another bug issue, really hope this doesn't bother you. ><

I noticed a repeatable crash (any recent ModernFix version, including most recent compiled) when

1. right clicking a tinkers crafting bench
2. visiting the tinkers tab in creative mode and hovering the mouse pointer over a crafting bench

I tried to add "tconstruct" as modid that bakes early, but that stopped the game from loading. "tconstruct:crafting_station" allowed me to boot but sadly didn't solve the problem.

Here's the crash log: 
[crash-2023-02-12_21.16.44-client.txt](https://github.com/embeddedt/ModernFix/files/10719085/crash-2023-02-12_21.16.44-client.txt)
And here is the entire log:
[latest.log](https://github.com/embeddedt/ModernFix/files/10719088/latest.log)

I also wonder if you may have any idea about this crash I am experiencing...however it seems like this crash is happening between the mod "Spoiled" and "Macaw's Furniture" and probably doesn't have anything to do with ModernFix. 
[crash-2023-02-12_23.19.34-server.txt](https://github.com/embeddedt/ModernFix/files/10719184/crash-2023-02-12_23.19.34-server.txt)

Apologies once again

**Comment by embeddedt** [comment] 2023-02-13 19:56
The first crash (and #17) should be fixed now. I agree that the second crash is likely not caused by ModernFix.

**Closed** 2023-02-13 19:55 UTC

**Comment by embeddedt** [comment] 2023-02-13 19:57
By the way, I do have a Discord channel if you're interested; it's linked on the [mod page](https://www.curseforge.com/minecraft/mc-mods/modernfix).
