### ISSUE TITLE
Dynamic DFU optimization breaks litematica

### ISSUE THREAD

**Issue by RaphiMC** [embeddedt/ModernFix#332] opened 2023-12-25 22:20 UTC
If you try to load any **.schematic** file with litematica it will be empty (I assume because blocks aren't being upgraded from legacy to modern format). Disabling Dynamic DFU fixes it

**Comment by embeddedt** [comment] 2023-12-28 00:13
It is probably caused by this Litematica mixin: https://github.com/maruohon/litematica/blob/pre-rewrite/fabric/1.20.x/src/main/java/fi/dy/masa/litematica/mixin/MixinBlockStateFlattening.java

In vanilla, that class is indirectly loaded at startup by DFU being initialized, and so the mixin's injector will run. With dynamic DFU enabled, it only loads when DFU is first invoked to upgrade a chunk - but Litematica probably doesn't use DFU directly, since it seems to be adding these entries to its own conversion map. 

I'll just [disable dynamic DFU automatically](https://github.com/embeddedt/ModernFix/commit/ae8cfbaa3d880a20b70a418f4ae276312fa30981) when Litematica is present.

**Comment by embeddedt** [comment] 2024-01-11 21:11
Should be fixed in 5.12.0.

**Closed as completed by embeddedt** 2024-01-11 21:11 UTC
Labels: fixed in beta
